### PR TITLE
Further improve php_syntax.sh

### PR DESCRIPTION
**Pull request by m0rff**
Use a complete script with correct error handling and a nice syntax.
This will also print the filename where the php syntax check failed.

### CODE REVIEW

**Review by felixkempf — CHANGES_REQUESTED** [review]
Please exclude all files in the vendor folder, as right now, it reports some bake templates with their unnormal php meta syntax as errors:
```
Blei:tm20 flix$ c php-syntax
> bin/php_syntax.sh
PHP Parse error:  syntax error, unexpected '<', expecting '{' in ./vendor/cakephp/bake/src/Template/Bake/Controller/component.ctp on line 17
Script bin/php_syntax.sh handling the php-syntax event returned with error code 255
```

**Comment by m0rff** [comment]
@felixkempf I added another commit to take files and folders as arguments
Usage: `./bin/php_syntax.sh path/to/directory/ path/to/file.php`

We can do `./bin/php_syntax.sh src/ tests/ index.php` e.g.

**Review by felixkempf — APPROVED** [review]

**Comment by felixkempf** [comment]
Well done, explicit whitelisting is always nicer

**Comment by felixkempf** [comment]
@m0rth1um please update the use of this script in the composer.json accordingly, then we are ready to merge

**Pull request merged**
